
(function(){
'use strict';
const routes=['dj','quests','comfort','travel','vision','pet','insights','creative','cinema','sleep'];
const labels={
en:{dj:'Mood DJ',quests:'Daily Quests',comfort:'My Comfort Zone',travel:'My Travel Map',vision:'My Vision Board',pet:'My Pet',insights:'My Life Insights',creative:'AI Creative Lab',cinema:'My Cinema & Gaming',sleep:'My Sleep & Dreams',add:'Add new',delete:'Delete',empty:'Nothing here yet — make it yours!',saved:'Saved to your space',cancel:'Cancel',save:'Save',remove:'Delete this item?',date:'Date',title:'Title',note:'Notes',name:'Name',photo:'Image URL (optional, HTTPS)',link:'Link (optional, HTTPS)',done:'Complete',upcoming:'Planned',back:'Back',optional:'Optional',privacy:'Saved in this browser. Export your data in Settings to back it up.',genre:'Category',custom:'Create your own',noMedical:'Personal reflections, not medical advice.',status:'Status',rating:'My rating',minutes:'minutes'},
fa:{dj:'دی‌جی حال‌وهوا',quests:'مأموریت‌های روزانه',comfort:'گوشه آرامش من',travel:'نقشه سفرهای من',vision:'تابلوی رویاها',pet:'حیوان خانگی من',insights:'گزارش زندگی من',creative:'آزمایشگاه خلاقیت',cinema:'فیلم و بازی‌های من',sleep:'خواب و رویاهای من',add:'افزودن',delete:'حذف',empty:'اینجا هنوز خالیه؛ به سلیقه خودت بسازش!',saved:'در فضای شخصیت ثبت شد',cancel:'انصراف',save:'ذخیره',remove:'این مورد حذف بشه؟',date:'تاریخ',title:'عنوان',note:'یادداشت',name:'نام',photo:'لینک عکس (اختیاری، HTTPS)',link:'لینک (اختیاری، HTTPS)',done:'انجام شد',upcoming:'برنامه‌ریزی‌شده',back:'بازگشت',optional:'اختیاری',privacy:'در همین مرورگر ذخیره می‌شه. برای پشتیبان‌گیری از تنظیمات خروجی بگیر.',genre:'دسته‌بندی',custom:'مورد دلخواه',noMedical:'اینها یادداشت‌های شخصی هستن، نه توصیه پزشکی.',status:'وضعیت',rating:'امتیاز من',minutes:'دقیقه'}
};
const definitions={
quests:[['title','text','Task / مأموریت',true],['emoji','text','Emoji / ایموجی'],['date','date','Date / تاریخ',true],['minutes','number','Minutes / دقیقه'],['note','textarea','Notes / توضیحات']],
comfort:[['title','text','Something that helps / چیز آرامش‌بخش',true],['emoji','text','Emoji / ایموجی'],['note','textarea','Why it matters / چرا دوستش داری']],
travel:[['title','text','Place / شهر یا مقصد',true],['country','text','Country / کشور'],['date','date','Travel date / تاریخ'],['kind','select','Type / نوع',[['visited','Visited / سفر رفته'],['wishlist','Dream destination / مقصد رویایی']]],['lat','number','Latitude (-90 to 90) / عرض جغرافیایی'],['lng','number','Longitude (-180 to 180) / طول جغرافیایی'],['note','textarea','Memory / خاطره']],
vision:[['title','text','Dream or goal / رویا یا هدف',true],['category','select','Category / دسته',[['life','Life / زندگی'],['work','Career / شغل'],['creative','Creative / خلاقیت'],['travel','Travel / سفر']]],['image','url','Image URL (HTTPS) / لینک عکس'],['note','textarea','Why it inspires you / دلیل اهمیت']],
pets:[['title','text','Pet name / اسم حیوان',true],['species','text','Type / نوع حیوان'],['birthday','date','Birthday / تولد'],['image','url','Photo URL (HTTPS) / لینک عکس'],['note','textarea','Little things you love / ویژگی‌های بامزه']],
petCare:[['petId','petselect','Pet / حیوان',true],['title','text','Care task / مراقبت',true],['date','date','Reminder date / تاریخ',true],['note','textarea','Notes / یادداشت']],
media:[['title','text','Title / عنوان',true],['kind','select','Kind / نوع',[['movie','Movie / فیلم'],['series','Series / سریال'],['animation','Animation / انیمیشن'],['game','Game / بازی']]],['status','select','Status / وضعیت',[['planned','Want to try / در لیست'],['inprogress','In progress / در حال تجربه'],['completed','Completed / تمام‌شده']]],['rating','number','Rating 0–10 / امتیاز'],['image','url','Poster URL (HTTPS) / لینک پوستر'],['note','textarea','Personal review / نظر شخصی']],
sleep:[['date','date','Night / تاریخ',true],['bed','time','Bedtime / ساعت خواب',true],['wake','time','Wake up / بیداری',true],['quality','select','Rest / کیفیت',[['5','Great / عالی'],['4','Good / خوب'],['3','Okay / معمولی'],['2','Restless / بی‌قرار'],['1','Poor / ضعیف']]],['dream','textarea','Dream journal / دفتر رویا']],
ideas:[['title','text','Your idea / ایده',true],['content','textarea','Describe it / توضیحات']]
};
let ctx=null, djMood='auto', creativityMode='game', creativeIdea=null, djMix=[], activePet='all', insightRange=7, breathing=false, busy=false;
const t=k=>(labels[ctx.state.lang]||labels.en)[k]||labels.en[k]||k;
const lang=(en,fa)=>ctx.state.lang==='fa'?fa:en;
const h=x=>ctx.esc(String(x??''));
const now=()=>new Date().toISOString();
const localDate=()=>ctx.today();
const id=()=>ctx.uid();
const sec=()=>ctx.state.extras;
const lists=['quests','comfort','travel','vision','pets','petCare','media','sleep'];
function init(){if(!ctx.state.extras||typeof ctx.state.extras!=='object'||Array.isArray(ctx.state.extras))ctx.state.extras={};for(const k of lists)if(!Array.isArray(sec()[k]))sec()[k]=[];}
function safe(url){if(!url)return '';try{const u=new URL(String(url));return u.protocol==='https:'&&!u.username&&!u.password&&u.hostname?u.href:'';}catch{return '';}}
function date(str){try{return new Date(str+'T12:00:00').toLocaleDateString(ctx.state.lang==='fa'?'fa-IR':'en-US',{year:'numeric',month:'short',day:'numeric'});}catch{return h(str||'');}}
function head(title,subtitle,add){return `<header class="extra-head"><div><span class="extra-eyebrow">MY HEALTH · ✦</span><h1>${h(title)}</h1><p>${h(subtitle)}</p></div>${add?`<button class="btn btn-primary" data-extra-add="${add}">＋ ${t('add')}</button>`:''}</header>`;}
function empty(key,emoji='✨'){return `<div class="extra-empty"><span>${emoji}</span><strong>${t('empty')}</strong><button class="btn btn-light btn-sm" data-extra-add="${key}">${t('add')} ＋</button></div>`;}
function save(){if(ctx.save())return true;return false;}
function insert(kind,item){init();sec()[kind].unshift({id:id(),time:now(),...item});if(!save()){sec()[kind].shift();return false;}return true;}
function buttons(kind,item){return `<button class="extra-trash" data-extra-delete="${kind}" data-id="${h(item.id)}" title="${t('delete')}" aria-label="${t('delete')}">✕</button>`;}
function img(url,fallback='✨'){let u=safe(url);return u?`<img loading="lazy" referrerpolicy="no-referrer" alt="" src="${h(u)}">`:`<span>${fallback}</span>`;}
function card(kind,item,icon='✨',body=''){return `<article class="extra-card">${buttons(kind,item)}<div class="extra-card-icon">${img(item.image,icon)}</div><h3>${h(item.title)}</h3>${body||''}</article>`;}
function formField([name,type,label,required]){const val=type==='date'?localDate():'';const options=Array.isArray(required)?required:null;const req=required===true?'required':'';if(type==='select')return `<label class="extra-field"><span>${h(label)}</span><select class="select" name="${name}">${options.map(([v,l])=>`<option value="${h(v)}">${h(l)}</option>`).join('')}</select></label>`;if(type==='petselect')return `<label class="extra-field"><span>${h(label)}</span><select class="select" name="${name}">${sec().pets.map(p=>`<option value="${h(p.id)}">${h(p.title)}</option>`).join('')}</select></label>`;if(type==='textarea')return `<label class="extra-field"><span>${h(label)}</span><textarea class="textarea" name="${name}" maxlength="4000" rows="4"></textarea></label>`;const limits=name==='lat'?'min="-90" max="90" step="any"':name==='lng'?'min="-180" max="180" step="any"':name==='rating'?'min="0" max="10" step=".5"':name==='minutes'?'min="0" max="1440"':'';return `<label class="extra-field"><span>${h(label)}</span><input class="input" type="${type}" name="${name}" ${limits} maxlength="${type==='text'?150:undefined}" value="${val}" ${req}></label>`;}
function addForm(kind){init();if(kind==='petCare'&&!sec().pets.length){ctx.toast(lang('Add a pet first.','اول یک حیوان اضافه کن.'));return;}const fields=definitions[kind];if(!fields)return;ctx.modal(lang('Add to your space','افزودن به فضای من'),`<form id="extrasForm" class="extra-form" data-kind="${kind}">${fields.map(formField).join('')}<div class="modal-actions"><button type="button" class="btn btn-ghost" data-action="close">${t('cancel')}</button><button type="submit" class="btn btn-primary">${t('save')}</button></div></form>`);}
const mediaFavorites=()=>ctx.state.favorites.filter(f=>['games','movies','anime'].includes(f.type));
const songs=()=>ctx.state.favorites.filter(f=>f.type==='music');
function renderDJ(){const music=songs(),mood=ctx.latestMood(),moodName=mood?mood.score>=4?'happy':mood.score<=2?'calm':'focus':'happy';const active=djMood==='auto'?moodName:djMood;
const vibe={happy:['happy','energy','other'],calm:['calm','nostalgic','other'],focus:['focus','calm','other'],energy:['energy','happy','other'],nostalgic:['nostalgic','calm','other']};const sorted=[...music].sort((a,b)=>(vibe[active]||vibe.happy).indexOf(a.vibe)-(vibe[active]||vibe.happy).indexOf(b.vibe));if(!djMix.length||djMood==='auto')djMix=sorted.slice(0,6);
return head(t('dj'),lang('A personal soundtrack chosen from the music you saved.','آهنگ‌های ذخیره‌شده‌ات، مناسب حال‌وهوای امروز.'))+`<div class="extra-feature dj-gradient"><div><span class="extra-eyebrow">${lang('YOUR MUSIC, YOUR MOOD','موزیک تو، حال‌وهوای تو')}</span><h2>🎧 ${lang('Find your rhythm','ریتم خودت رو پیدا کن')}</h2><p>${music.length} ${lang('songs in your library','آهنگ در کتابخانه تو')}</p><button class="btn btn-white" data-nav="music">${lang('Manage my music','مدیریت موزیک‌ها')} ↗</button></div><div class="extra-hero-emoji">🎵</div></div>
<div class="extra-toolbar"><span>${lang('Choose a vibe:','انتخاب حال‌وهوا:')}</span>${[['auto','✨',lang('My current mood','حال امروز من')],['happy','☀️',lang('Happy','شاد')],['calm','🌿',lang('Calm','آروم')],['focus','🧠',lang('Focus','تمرکز')],['energy','⚡',lang('Energy','انرژی')],['nostalgic','🌙',lang('Nostalgic','نوستالژی')]].map(([v,e,l])=>`<button class="chip ${v===djMood?'selected':''}" data-extra-dj="${v}">${e} ${l}</button>`).join('')}</div>
<div class="extra-section-title">🎼 ${lang('Your mood mix','میکس مخصوص حال تو')} <button class="btn btn-light btn-sm" data-extra-shuffle>🔀 ${lang('Shuffle','ترکیب تازه')}</button></div>${music.length?`<div class="extra-list">${djMix.map((x,i)=>`<div class="extra-list-item"><div class="extra-mini-art">${img(x.cover,'🎵')}</div><div><strong>${h(x.name)}</strong><small>${h(x.artist||lang('Unknown artist','هنرمند نامشخص'))}</small></div><span class="extra-number">${i+1}</span>${safe(x.link)?`<a class="btn btn-light btn-sm" href="${h(safe(x.link))}" target="_blank" rel="noopener noreferrer">${lang('Listen ↗','گوش دادن ↗')}</a>`:''}</div>`).join('')}</div>`:`<div class="extra-empty">🎧 <p>${lang('Add songs in My Music and Mood DJ will build a playlist from them.','اول در بخش موزیک‌ها آهنگ اضافه کن تا بر اساس حال‌وهوات پلی‌لیست ساخته بشه.')}</p><button class="btn btn-primary" data-nav="music">${lang('Add music','افزودن موزیک')}</button></div>`}<p class="extra-footnote">${lang('Suggestions are made on your device. Playback opens your saved music links.','پیشنهادها در مرورگر خودت ساخته می‌شن؛ پخش از طریق لینک‌هایی که ذخیره کردی انجام می‌شه.')}</p>`;}
const questTemplates=[['🌿','Take a short walk','یک پیاده‌روی کوتاه',15],['🎨','Make a quick sketch','یک طرح کوچیک بکش',15],['🎵','Listen to favorite music','به موزیک محبوبت گوش بده',10],['📚','Read a few pages','چند صفحه کتاب بخون',15],['🌼','Write something positive','یک خاطره قشنگ بنویس',10],['🎮','Enjoy a short gaming break','یک استراحت کوتاه با بازی',20]];
function renderQuests(){let all=sec().quests,day=all.filter(q=>q.date===localDate()),done=day.filter(q=>q.done).length,xp=all.filter(q=>q.done).reduce((s,q)=>s+(Number(q.xp)||20),0);
return head(t('quests'),lang('Small adventures. Your pace, your rules.','مأموریت‌های کوچیک، با سرعت و سلیقه خودت.'),'quests')+`<div class="extra-feature quest-gradient"><div><span class="extra-eyebrow">${lang('TODAY’S ADVENTURE','ماجراجویی امروز')}</span><h2>🏆 ${xp} XP</h2><p>${done}/${day.length} ${lang('quests completed today','مأموریت انجام‌شده امروز')}</p><div class="goal-line"><i style="width:${day.length?done/day.length*100:0}%"></i></div></div><div class="extra-hero-emoji">🏅</div></div>
<h2 class="extra-section-title">${lang('Today’s quests','مأموریت‌های امروز')}</h2>${day.length?`<div class="extra-list">${day.map(q=>`<article class="extra-list-item"><span class="extra-list-emoji">${h(q.emoji||'⭐')}</span><div><strong ${q.done?'style="text-decoration:line-through;opacity:.6"':''}>${h(q.title)}</strong><small>${q.minutes?Number(q.minutes)+' '+t('minutes')+' · ':''}20 XP${q.note?' · '+h(q.note):''}</small></div><label><input type="checkbox" class="extra-check" data-extra-quest="${h(q.id)}" ${q.done?'checked':''} aria-label="${t('done')}"></label>${buttons('quests',q)}</article>`).join('')}</div>`:empty('quests','🎯')}
<h2 class="extra-section-title">${lang('Pick a mini-quest','یک مأموریت کوچیک انتخاب کن')}</h2><div class="extra-grid">${questTemplates.map(([emoji,en,fa,mins],i)=>`<button class="extra-suggestion" data-extra-quest-template="${i}"><span>${emoji}</span><strong>${lang(en,fa)}</strong><small>${mins} ${t('minutes')} · +20 XP</small></button>`).join('')}</div><p class="extra-footnote">${lang('XP celebrates what you choose to do, not a daily obligation.','XP فقط برای جشن گرفتن انتخاب‌های خودته؛ هیچ اجباری برای انجام روزانه نیست.')}</p>`;}
function renderComfort(){const list=sec().comfort,calm=songs().filter(s=>['calm','nostalgic','focus'].includes(s.vibe)).slice(0,3);return head(t('comfort'),lang('Your own collection of gentle moments and comforting favorites.','مجموعه‌ای شخصی از چیزهایی که بهت احساس آرامش می‌دن.'),'comfort')+`<section class="extra-feature comfort-gradient"><div><span class="extra-eyebrow">${lang('A LITTLE SPACE FOR YOU','یک گوشه مخصوص خودت')}</span><h2>🌿 ${lang('It’s okay to slow down','گاهی می‌شه آروم‌تر پیش رفت')}</h2><p>${lang('You can simply stay here, listen to music or remember something nice.','می‌تونی اینجا چند لحظه بمونی، موزیک گوش بدی یا به یک خاطره خوب فکر کنی.')}</p></div><div class="extra-hero-emoji">☁️</div></section>
<div class="extra-columns"><section class="card"><h2 class="card-title">🫧 ${lang('Breathing space','فضای تنفس')}</h2><div class="extra-breath-wrap"><div class="extra-breath ${breathing?'is-breathing':''}">🌸</div></div><p class="text-center muted">${breathing?lang('Follow a comfortable, easy rhythm. Stop anytime.','با ریتم راحت خودت نفس بکش؛ هر وقت خواستی متوقف کن.'):lang('Take a peaceful moment, only if it feels comfortable.','اگر دوست داری، چند لحظه برای آرامش خودت وقت بذار.')}</p><button class="btn btn-primary w-100" data-extra-breathe>${breathing?lang('Stop','توقف'):lang('Start gentle breathing','شروع تنفس آروم')}</button></section>
<section class="card"><h2 class="card-title">🎵 ${lang('Soothing soundtrack','موزیک‌های آرامش‌بخش')}</h2>${calm.length?calm.map(x=>`<div class="extra-list-item"><span>🎧</span><div><strong>${h(x.name)}</strong><small>${h(x.artist||'')}</small></div>${safe(x.link)?`<a href="${h(safe(x.link))}" target="_blank" rel="noopener noreferrer" class="btn btn-light btn-sm">↗</a>`:''}</div>`).join(''):`<p class="helper">${lang('Tag songs Calm in My Music to see them here.','در بخش موزیک آهنگ‌ها رو با حال‌وهوای آروم ذخیره کن تا اینجا نمایش داده بشن.')}</p>`}</section></div>
<h2 class="extra-section-title">${lang('My comfort collection','چیزهای آرامش‌بخش من')}</h2>${list.length?`<div class="extra-grid">${list.map(x=>card('comfort',x,h(x.emoji||'💜'),x.note?`<p>${h(x.note)}</p>`:'' )).join('')}</div>`:empty('comfort','💜')}<p class="extra-footnote">${t('noMedical')}</p>`;}
function mapSvg(){const trips=sec().travel.filter(x=>Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng))&&x.lat!==''&&x.lng!==''&&Number(x.lat)<=90&&Number(x.lat)>=-90&&Number(x.lng)<=180&&Number(x.lng)>=-180);const dots=trips.map(x=>{const px=((Number(x.lng)+180)/360*860),py=((90-Number(x.lat))/180*390);return `<g class="extra-map-pin" role="button" tabindex="0" data-extra-map-pin="${h(x.id)}" aria-label="${h(x.title)}" style="cursor:pointer"><circle cx="${px}" cy="${py}" r="11" fill="${x.kind==='wishlist'?'#ff8da8':'#7055df'}" opacity=".2"/><circle cx="${px}" cy="${py}" r="5" fill="${x.kind==='wishlist'?'#f56d9c':'#7258e6'}" stroke="white" stroke-width="2"><title>${h(x.title)}</title></circle></g>`;}).join('');return `<svg viewBox="0 0 860 390" class="extra-world" role="img" aria-label="${lang('Stylized world map with your manually positioned places','نقشه شماتیک جهان با موقعیت‌های ثبت‌شده توسط تو')}"><defs><linearGradient id="sea" x2="1" y2="1"><stop stop-color="#ecf3ff"/><stop offset="1" stop-color="#e7f9f3"/></linearGradient></defs><rect width="860" height="390" rx="23" fill="url(#sea)"/><g stroke="#d8e5ef" fill="none" stroke-width="1">${[97,195,292].map(y=>`<path d="M0 ${y}H860"/>`).join('')}${[143,286,430,573,716].map(x=>`<path d="M${x} 0V390"/>`).join('')}</g><g fill="#cbdccf" stroke="#b3cebf" stroke-width="1.5"><path d="M50 99 95 58 185 52 210 83 250 86 265 130 230 157 210 190 171 199 149 162 108 154 85 128 50 120Z"/><path d="M193 177 234 176 269 206 273 251 250 304 229 343 209 327 206 271 193 238Z"/><path d="M365 86 413 66 446 90 472 81 503 59 568 60 587 81 640 78 705 104 752 110 761 142 705 151 662 178 627 167 596 195 555 190 521 167 491 168 457 144 432 143 409 122 380 130Z"/><path d="M431 166 490 176 519 211 498 274 469 291 440 256 425 208Z"/><path d="M679 274 746 265 794 293 784 330 722 337 680 315Z"/><path d="M331 47 354 39 370 60 352 78 329 71Z M785 163 804 177 813 201 805 222 789 207Z"/></g>${dots}</svg>`;}
function renderTravel(){const items=sec().travel;return head(t('travel'),lang('Pin places you visited and dream destinations; save memories along the way.','جاهایی که رفتی یا دوست داری بری رو همراه خاطراتت روی نقشه ثبت کن.'),'travel')+`<div class="extra-feature travel-gradient"><div><span class="extra-eyebrow">${lang('YOUR LITTLE WORLD','دنیای شخصی تو')}</span><h2>🌎 ${items.filter(x=>x.kind==='visited').length} ${lang('places visited','مقصد تجربه‌شده')}</h2><p>${items.filter(x=>x.kind==='wishlist').length} ${lang('dream destinations','مقصد رویایی')}</p></div><div class="extra-hero-emoji">✈️</div></div><section class="extra-map-card">${mapSvg()}<p class="extra-footnote">${lang('Stylized map. Enter approximate latitude and longitude to place a pin. No location access is requested.','این نقشه شماتیکه؛ برای نمایش نشان، مختصات تقریبی رو دستی وارد کن. دسترسی به موقعیت مکانی درخواست نمی‌شه.')}</p></section><h2 class="extra-section-title">${lang('My places','مقصدهای من')}</h2>${items.length?`<div class="extra-grid">${items.map(x=>card('travel',x,x.kind==='wishlist'?'🌈':'📍',`<p>${h(x.country||'')} ${x.date?' · '+h(date(x.date)):''}</p><span class="micro-label">${x.kind==='wishlist'?lang('Wishlist','رویایی'):lang('Visited','رفته‌ام')}</span>${x.note?`<p>${h(x.note)}</p>`:''}`)).join('')}</div>`:empty('travel','🌍')}`;}
function renderVision(){const items=sec().vision;return head(t('vision'),lang('A colorful board for what you hope to create and experience.','یک تابلوی رنگارنگ برای رویاها و هدف‌هات.'),'vision')+`<div class="extra-feature vision-gradient"><div><h2>🌈 ${lang('Your future, in your colors','آینده تو، با رنگ‌های خودت')}</h2><p>${lang('Collect goals, images and the little reasons they inspire you.','هدف‌ها، عکس‌ها و چیزهایی که بهت انگیزه می‌دن رو کنار هم بچین.')}</p></div><div class="extra-hero-emoji">✦</div></div>${items.length?`<div class="extra-vision-grid mt-28">${items.map((x,i)=>`<article class="extra-vision-tile v${i%5}">${buttons('vision',x)}<div class="extra-vision-art">${img(x.image,['✨','🌿','💜','🌸','🚀'][i%5])}</div><div class="extra-vision-info"><span class="micro-label">${h(x.category||'life')}</span><h3>${h(x.title)}</h3>${x.note?`<p>${h(x.note)}</p>`:''}<button class="btn btn-sm ${x.done?'btn-primary':'btn-light'}" data-extra-toggle="vision" data-id="${h(x.id)}">${x.done?'✓ '+t('done'):lang('Mark achieved','ثبت تحقق هدف')}</button></div></article>`).join('')}</div>`:empty('vision','🌈')}<p class="extra-footnote">${lang('Images load from their source URL. Only use links you trust.','عکس‌ها از لینک اصلی دریافت می‌شن؛ فقط لینک‌هایی که بهشون اعتماد داری وارد کن.')}</p>`;}
function renderPet(){const pets=sec().pets,care=sec().petCare,visible=activePet==='all'?care:care.filter(x=>x.petId===activePet);return head(t('pet'),lang('A cozy space for your furry, feathered or scaly companions.','یک فضای گرم برای دوستان پشمالو یا کوچولوهات.'),'pets')+`<div class="extra-feature pet-gradient"><div><h2>🐾 ${lang('Little paws, big love','پنجه‌های کوچیک، عشق بزرگ')}</h2><p>${lang('Celebrate pet memories and keep your own care reminders.','خاطرات حیواناتت رو ثبت کن و یادآور مراقبت بساز.')}</p></div><div class="extra-hero-emoji">🐱</div></div><h2 class="extra-section-title">${lang('My companions','دوست‌های کوچولوی من')}</h2>${pets.length?`<div class="extra-grid">${pets.map(p=>card('pets',p,'🐈',`<p>${h(p.species||'')} ${p.birthday?' · 🎂 '+h(date(p.birthday)):''}</p>${p.note?`<p>${h(p.note)}</p>`:''}<button class="btn btn-light btn-sm" data-extra-pet="${h(p.id)}">${lang('Care reminders','یادآورها')}</button>`)).join('')}</div>`:empty('pets','🐾')}
<div class="extra-section-title">📅 ${lang('Care reminders','یادآورهای مراقبت')} <button class="btn btn-light btn-sm" data-extra-add="petCare">＋ ${t('add')}</button></div><div class="extra-toolbar"><button class="chip ${activePet==='all'?'selected':''}" data-extra-pet="all">${lang('All pets','همه')}</button>${pets.map(p=>`<button class="chip ${activePet===p.id?'selected':''}" data-extra-pet="${h(p.id)}">${h(p.title)}</button>`).join('')}</div>${visible.length?`<div class="extra-list">${visible.sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(x=>`<div class="extra-list-item"><span class="extra-list-emoji">🩺</span><div><strong>${h(x.title)}</strong><small>${h(pets.find(p=>p.id===x.petId)?.title||'')} · ${h(date(x.date))}${x.note?' · '+h(x.note):''}</small></div><button class="btn btn-sm ${x.done?'btn-primary':'btn-light'}" data-extra-toggle="petCare" data-id="${h(x.id)}">${x.done?'✓':lang('Mark done','انجام شد')}</button>${buttons('petCare',x)}</div>`).join('')}</div>`:empty('petCare','📅')}<p class="extra-footnote">${lang('Reminders appear inside this app; there are no background notifications or veterinary recommendations.','یادآورها فقط داخل اپ نمایش داده می‌شن؛ اعلان پس‌زمینه یا توصیه دامپزشکی ارائه نمی‌شه.')}</p>`;}
function insightBars(data,max=5){return `<div class="extra-chart">${data.map(x=>`<div class="extra-chart-col"><div class="extra-chart-bar" style="height:${x.value===null?3:Math.max(4,Math.min(100,x.value/max*100))}%"><span>${x.value===null?'—':h(x.value)}</span></div><small>${h(x.label)}</small></div>`).join('')}</div>`;}
function renderInsights(){const days=Array.from({length:insightRange},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(insightRange-1-i));return d.toLocaleDateString('en-CA')=== 'x'?null:{key:new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),label:d.toLocaleDateString(ctx.state.lang==='fa'?'fa-IR':'en-US',{month:'numeric',day:'numeric'})};});const mood=days.map(d=>{let entries=ctx.state.moods.filter(x=>x.time?.slice(0,10)===d.key).sort((a,b)=>b.time.localeCompare(a.time));return {...d,value:entries.length?Number(entries[0].score):null};});const water=days.map(d=>({...d,value:Number(ctx.state.wellness[d.key]?.water||0)}));const sleep=days.map(d=>({...d,value:sec().sleep.find(x=>x.date===d.key)?.hours??null}));const completed=sec().quests.filter(q=>q.done&&days.some(d=>d.key===q.date)).length;const ratings=mood.filter(x=>x.value!==null);const avg=ratings.length?(ratings.reduce((a,b)=>a+b.value,0)/ratings.length).toFixed(1):'—';
return head(t('insights'),lang('A personal view of what you actually recorded — no guesswork.','نمایی از چیزهایی که خودت ثبت کردی، بدون حدس یا قضاوت.'))+`<div class="extra-feature insights-gradient"><div><h2>📊 ${lang('Your days in perspective','روزهای تو در یک نگاه')}</h2><p>${lang('Notice patterns over time; these are associations, not causes.','الگوهای روزهای خودت رو ببین؛ ارتباط‌ها به معنی علت و معلول نیستن.')}</p></div><div class="extra-hero-emoji">📈</div></div><div class="extra-toolbar mt-28">${[7,14,30].map(n=>`<button class="chip ${insightRange===n?'selected':''}" data-extra-range="${n}">${n} ${lang('days','روز')}</button>`).join('')}</div><div class="extra-stats"><div><strong>${ratings.length}</strong><small>${lang('Mood check-ins days','روز با ثبت احساس')}</small></div><div><strong>${avg}</strong><small>${lang('Average mood (0–5)','میانگین حال‌وهوا (۰–۵)')}</small></div><div><strong>${completed}</strong><small>${lang('Completed quests','مأموریت انجام‌شده')}</small></div><div><strong>${sec().sleep.filter(x=>days.some(d=>d.key===x.date)).length}</strong><small>${lang('Sleep logs','ثبت خواب')}</small></div></div>
<div class="extra-columns mt-20"><section class="card"><h3>💗 ${lang('Mood check-ins','حال‌وهوای ثبت‌شده')}</h3>${insightBars(mood,5)}<p class="helper">${lang('Blank means you did not log a mood.','روز خالی یعنی احساسی ثبت نکردی.')}</p></section><section class="card"><h3>💧 ${lang('Water logs (glasses)','ثبت آب (لیوان)')}</h3>${insightBars(water,Math.max(8,...water.map(x=>x.value)))}<p class="helper">${lang('Manual entries only.','فقط اطلاعات ثبت‌شده دستی.')}</p></section></div><section class="card mt-20"><h3>🌙 ${lang('Hours slept','ساعت‌های خواب')}</h3>${insightBars(sleep,12)}</section><div class="notice mt-20">${t('noMedical')} ${lang('These charts summarize your own entries; they cannot infer your health or the causes of your mood.','این نمودارها فقط اطلاعات ثبت‌شده خودت رو خلاصه می‌کنن؛ وضعیت سلامت یا دلیل احساسات رو تشخیص نمی‌دن.')}</div>`;}
const creativeTemplates={
game:[['game','🎮','cozy','world'],['puzzle','🧩','mysterious','puzzle'],['story','🎬','cinematic','adventure']],
film:[['film','🎥','dreamlike','scene'],['animation','🎨','colorful','short film'],['camera','📷','nostalgic','photo essay']],
art:[['poster','🖌️','retro-futuristic','poster'],['character','🦄','whimsical','character'],['space','🌌','cosmic','world']],
writing:[['story','✍️','heartwarming','story'],['travel','🗺️','imaginative','travel diary'],['music','🎹','playful','song concept']]
};
function localIdea(){const picks=creativeTemplates[creativityMode]||creativeTemplates.game;const pick=picks[Math.floor(Math.random()*picks.length)];const fav=ctx.state.favorites[Math.floor(Math.random()*ctx.state.favorites.length)]?.name;let en=`Create a ${pick[2]} ${pick[3]} inspired by ${fav||'a place you have always wanted to visit'}. Give it a surprising twist and design three memorable details.`;let fa=`یک ${pick[3]} با حال‌وهوای ${pick[2]} بساز که از ${fav||'یک مقصد رویایی'} الهام گرفته باشه. یک چرخش داستانی جالب و سه جزئیات به‌یادموندنی براش طراحی کن.`;return {title:lang(`Your ${pick[3]} challenge`,`چالش ${pick[3]} تو`),content:lang(en,fa),emoji:pick[1],kind:'creative'};}
function renderCreative(){return head(t('creative'),lang('Turn your interests into original challenges, stories and little experiments.','از علاقه‌مندی‌هات چالش‌های خلاقانه، داستان و تجربه‌های تازه بساز.'))+`<div class="extra-feature creative-gradient"><div><span class="extra-eyebrow">${lang('IDEAS ARE EVERYWHERE','ایده همه‌جا هست')}</span><h2>🤖 ${lang('Make something wonderful','یک چیز جالب خلق کن')}</h2><p>${lang('Mix favorite worlds, creative formats and unexpected prompts.','دنیاهای محبوبت، قالب‌های خلاقانه و ایده‌های غیرمنتظره رو ترکیب کن.')}</p></div><div class="extra-hero-emoji">🎨</div></div>
<div class="extra-toolbar mt-28">${[['game','🎮',lang('Game design','طراحی بازی')],['film','🎥',lang('Film & animation','فیلم و انیمیشن')],['art','🖌️',lang('Visual art','هنر تصویری')],['writing','✍️',lang('Writing','نویسندگی')]].map(([k,e,l])=>`<button class="chip ${creativityMode===k?'selected':''}" data-extra-creative-mode="${k}">${e} ${l}</button>`).join('')}</div>
<div class="card extra-idea-card"><span class="extra-idea-emoji">${creativeIdea?.emoji||'✨'}</span><h2>${h(creativeIdea?.title||lang('A spark is waiting for you','یک جرقه تازه منتظرته'))}</h2><p>${h(creativeIdea?.content||lang('Pick a creative category and generate a new challenge tailored to your favorites.','یک زمینه خلاقانه انتخاب کن و یک چالش تازه متناسب با علاقه‌مندی‌هات بساز.'))}</p><div class="flex-wrap"><button class="btn btn-primary" data-extra-create>✦ ${lang('Generate a challenge','ساخت چالش')}</button>${creativeIdea?`<button class="btn btn-light" data-extra-save-idea>💡 ${lang('Save to Ideas','ثبت در ایده‌ها')}</button>`:''}</div></div>
<div class="card mt-20"><h3>✨ ${lang('Optional generative AI','هوش مصنوعی مولد اختیاری')}</h3><p class="helper">${lang('To use a real AI model, first connect your own private backend in Settings. The prompt will include your chosen category and favorite titles, only when you explicitly request it.','برای استفاده از مدل واقعی AI، ابتدا بک‌اند خصوصی خودت رو در تنظیمات وصل کن. فقط وقتی درخواست بدی، دسته انتخابی و عنوان علاقه‌مندی‌ها ارسال می‌شن.')}</p><label class="extra-consent"><input id="creativeConsent" type="checkbox"> ${lang('I agree to send my selected category and favorite titles to my configured AI backend for this request.','موافقم دسته انتخابی و عنوان علاقه‌مندی‌هام فقط برای همین درخواست به بک‌اند تنظیم‌شده ارسال بشن.')}</label><button class="btn btn-light mt-15" data-extra-ai-create ${busy?'disabled':''}>${busy?'…':'🤖 '+lang('Generate with AI','ساخت با AI')}</button></div>`;}
function renderCinema(){const items=sec().media,legacy=mediaFavorites();return head(t('cinema'),lang('Watchlists, game backlogs and your own mini-reviews.','فهرست تماشا و بازی‌ها، همراه با نظر و امتیاز شخصی خودت.'),'media')+`<div class="extra-feature cinema-gradient"><div><h2>🎮 ${lang('Your entertainment universe','دنیای سرگرمی خودت')}</h2><p>${items.length} ${lang('titles in your watchlist & backlog','عنوان در فهرست شخصی تو')}</p></div><div class="extra-hero-emoji">🎬</div></div><h2 class="extra-section-title">${lang('My watchlist & game backlog','فهرست فیلم‌ها و بازی‌ها')}</h2>${items.length?`<div class="extra-grid">${items.map(x=>card('media',x,x.kind==='game'?'🎮':'🎬',`<p>${h(x.kind||'movie')} · ${h(x.status||'planned')}${x.rating!==''&&x.rating!=null?' · ★ '+h(x.rating)+'/10':''}</p>${x.note?`<p>${h(x.note)}</p>`:''}<button class="btn btn-sm btn-light" data-extra-media-next="${h(x.id)}">${x.status==='planned'?lang('Start','شروع'):x.status==='inprogress'?lang('Mark complete','ثبت اتمام'):lang('Watch again','تجربه دوباره')}</button>`)).join('')}</div>`:empty('media','🍿')}
<h2 class="extra-section-title">${lang('From your favorites','از علاقه‌مندی‌های قبلی تو')}</h2>${legacy.length?`<div class="extra-grid">${legacy.map(x=>`<article class="extra-card"><div class="extra-card-icon">${x.type==='games'?'🎮':x.type==='anime'?'🦊':'🎬'}</div><h3>${h(x.name)}</h3><p>${h(x.notes||'')}</p><span class="micro-label">${h(x.type)}</span></article>`).join('')}</div>`:`<div class="notice">${lang('Your favorite movies, animation and games from My Favorites appear here automatically.','فیلم‌ها، انیمیشن‌ها و بازی‌هایی که در علاقه‌مندی‌ها ذخیره کردی، اینجا نمایش داده می‌شن.')}</div>`}`;}
function sleepHours(bed,wake){const [bh,bm]=String(bed).split(':').map(Number),[wh,wm]=String(wake).split(':').map(Number);if([bh,bm,wh,wm].some(x=>!Number.isFinite(x)))return null;let diff=(wh*60+wm)-(bh*60+bm);if(diff<=0)diff+=1440;return +(diff/60).toFixed(1);}
function renderSleep(){const items=[...sec().sleep].sort((a,b)=>b.date.localeCompare(a.date));const hours=items.filter(x=>Number.isFinite(x.hours)).slice(0,7),avg=hours.length?(hours.reduce((s,x)=>s+x.hours,0)/hours.length).toFixed(1):'—';return head(t('sleep'),lang('A simple sleep diary and a safe place to remember your dreams.','دفتر ثبت خواب و جایی برای نگهداری رویاهایی که دیدی.'),'sleep')+`<div class="extra-feature sleep-gradient"><div><span class="extra-eyebrow">${lang('SLEEP & DREAMS','خواب و رویاها')}</span><h2>🌙 ${avg} ${lang('h average (last 7 logs)','ساعت میانگین (۷ ثبت اخیر)')}</h2><p>${items.length} ${lang('nights recorded','شب ثبت‌شده')}</p></div><div class="extra-hero-emoji">☁️</div></div><h2 class="extra-section-title">${lang('Recent nights','شب‌های گذشته')}</h2>${items.length?`<div class="extra-list">${items.map(x=>`<article class="extra-list-item"><span class="extra-list-emoji">🌜</span><div><strong>${h(date(x.date))} · ${h(x.hours)} ${lang('hours','ساعت')}</strong><small>${h(x.bed)} → ${h(x.wake)} · ${['','😴','🌧️','🙂','😊','🌟'][Number(x.quality)||3]}</small>${x.dream?`<p class="extra-dream">${h(x.dream)}</p>`:''}</div>${buttons('sleep',x)}</article>`).join('')}</div>`:empty('sleep','🌙')}<div class="notice mt-20">${lang('Calculated from the bedtime and wake-up times you enter. No dream interpretation or medical assessment.','ساعت خواب از زمان‌هایی که خودت ثبت می‌کنی محاسبه می‌شه؛ تعبیر خواب یا ارزیابی پزشکی انجام نمی‌شه.')}</div>`;}
const views={dj:renderDJ,quests:renderQuests,comfort:renderComfort,travel:renderTravel,vision:renderVision,pet:renderPet,insights:renderInsights,creative:renderCreative,cinema:renderCinema,sleep:renderSleep};
function render(route,context){ctx=context;init();return (views[route]||renderQuests)();}
function refresh(){ctx.render();}
function click(event){if(!ctx)return false;const el=event.target.closest('[data-extra-add],[data-extra-delete],[data-extra-toggle],[data-extra-dj],[data-extra-shuffle],[data-extra-quest-template],[data-extra-pet],[data-extra-breathe],[data-extra-range],[data-extra-creative-mode],[data-extra-create],[data-extra-save-idea],[data-extra-ai-create],[data-extra-media-next],[data-extra-map-pin]');if(!el)return false;
if(el.dataset.extraAdd){addForm(el.dataset.extraAdd);return true;}
if(el.dataset.extraDelete){let k=el.dataset.extraDelete;if(lists.includes(k)&&confirm(t('remove'))){const before=sec()[k];sec()[k]=before.filter(x=>String(x.id)!==el.dataset.id);if(!save())sec()[k]=before;else{if(k==='pets'){sec().petCare=sec().petCare.filter(x=>x.petId!==el.dataset.id);save();}refresh();}}return true;}
if(el.dataset.extraToggle){let x=sec()[el.dataset.extraToggle]?.find(q=>String(q.id)===el.dataset.id);if(x){x.done=!x.done;save();refresh();}return true;}
if(el.dataset.extraDj){djMood=el.dataset.extraDj;djMix=[];refresh();return true;}
if(el.hasAttribute('data-extra-shuffle')){const a=[...songs()].sort(()=>Math.random()-.5);djMix=a.slice(0,6);djMood='custom';refresh();return true;}
if(el.dataset.extraQuestTemplate!==undefined){let q=questTemplates[Number(el.dataset.extraQuestTemplate)];if(q&&insert('quests',{title:lang(q[1],q[2]),emoji:q[0],minutes:q[3],date:localDate(),done:false,xp:20})){refresh();ctx.toast(t('saved'));}return true;}
if(el.dataset.extraPet){activePet=el.dataset.extraPet;refresh();return true;}
if(el.hasAttribute('data-extra-breathe')){breathing=!breathing;refresh();return true;}
if(el.dataset.extraRange){insightRange=[7,14,30].includes(Number(el.dataset.extraRange))?Number(el.dataset.extraRange):7;refresh();return true;}
if(el.dataset.extraCreativeMode){creativityMode=el.dataset.extraCreativeMode;refresh();return true;}
if(el.hasAttribute('data-extra-create')){creativeIdea=localIdea();refresh();return true;}
if(el.hasAttribute('data-extra-save-idea')){if(creativeIdea){ctx.state.ideas.push({id:id(),title:creativeIdea.title,content:creativeIdea.content,kind:'creative',time:now()});if(!save())ctx.state.ideas.pop();else ctx.toast(t('saved'));}return true;}
if(el.dataset.extraMediaNext){let x=sec().media.find(q=>String(q.id)===el.dataset.extraMediaNext);if(x){x.status=x.status==='planned'?'inprogress':x.status==='inprogress'?'completed':'planned';save();refresh();}return true;}
if(el.dataset.extraMapPin){const place=sec().travel.find(x=>String(x.id)===el.dataset.extraMapPin);if(place)ctx.modal(place.title,`<div class="stack"><p>📍 ${h(place.country||'')} ${place.date?' · '+h(date(place.date)):''}</p>${place.note?`<p>${h(place.note)}</p>`:''}<span class="micro-label">${place.kind==='wishlist'?lang('Dream destination','مقصد رویایی'):lang('Visited','سفر رفته')}</span></div>`);return true;}
if(el.hasAttribute('data-extra-ai-create')){requestAI();return true;}
return false;
}
function change(event){const el=event.target;if(el?.dataset?.extraQuest){let q=sec().quests.find(x=>String(x.id)===el.dataset.extraQuest);if(q){q.done=!!el.checked;save();refresh();}return true;}return false;}
function submit(form,fd){if(form.id!=='extrasForm')return false;const kind=form.dataset.kind;if(!definitions[kind])return false;let item={};for(const [name,type] of definitions[kind]){const raw=fd.get(name);item[name]=String(raw||'').trim().slice(0,type==='textarea'?4000:500);if(type==='url'&&item[name]&&!safe(item[name])){ctx.toast(lang('Enter a valid HTTPS image URL.','لینک تصویر HTTPS معتبر وارد کن.'));return true;}}
if(kind==='travel'){if(item.lat!==''&&(!Number.isFinite(Number(item.lat))||Number(item.lat)<-90||Number(item.lat)>90)||item.lng!==''&&(!Number.isFinite(Number(item.lng))||Number(item.lng)<-180||Number(item.lng)>180)){ctx.toast(lang('Coordinates are outside the world map.','مختصات خارج از محدوده نقشه است.'));return true;}}
if(kind==='sleep'){if(!item.date||!item.bed||!item.wake)return true;item.hours=sleepHours(item.bed,item.wake);}
if(kind==='media'&&item.rating!==''){if(Number(item.rating)<0||Number(item.rating)>10)return true;item.rating=Number(item.rating);}
if(kind==='quests'){item.date=item.date||localDate();item.done=false;item.xp=20;}
if(kind==='petCare')item.done=false;
const mainTitle=kind==='sleep'?item.date:kind==='petCare'?item.title:item.title;
if(kind!=='sleep'&&!mainTitle){ctx.toast(lang('Please add a title.','لطفاً عنوان وارد کن.'));return true;}
if(insert(kind,item)){ctx.closeModal();refresh();ctx.toast(t('saved'));}return true;}
async function requestAI(){if(busy)return;const checkbox=document.querySelector('#creativeConsent');if(!checkbox?.checked){ctx.toast(lang('Please check the consent box for this one AI request.','برای همین درخواست، گزینه رضایت رو فعال کن.'));return;}const endpoint=ctx.state.aiEndpoint;if(!endpoint||!safe(endpoint)){ctx.toast(lang('Connect a private HTTPS AI backend in Settings first.','اول بک‌اند خصوصی HTTPS رو در تنظیمات وصل کن.'));return;}let u;try{u=new URL(endpoint);if(!/\/api\/plan\/?$/.test(u.pathname))throw Error('endpoint');u.pathname=u.pathname.replace(/plan\/?$/,'create');}catch{ctx.toast(lang('Use an AI endpoint ending in /api/plan in Settings.','در تنظیمات لینک بک‌اند با انتهای /api/plan وارد کن.'));return;}busy=true;refresh();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),16000);try{const resp=await fetch(u.href,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',cache:'no-store',signal:controller.signal,body:JSON.stringify({category:creativityMode,lang:ctx.state.lang,favorites:ctx.state.favorites.slice(-8).map(x=>({name:String(x.name).slice(0,100),type:x.type}))})});if(!resp.ok)throw Error('AI unavailable');const payload=await resp.json();if(typeof payload.title!=='string'||typeof payload.content!=='string')throw Error('format');creativeIdea={title:payload.title.slice(0,120),content:payload.content.slice(0,2000),emoji:'🤖'};ctx.toast(lang('AI idea is ready.','ایده AI آماده شد.'));}catch{ctx.toast(lang('AI unavailable. Your on-device generator still works.','سرویس AI در دسترس نیست؛ ایده‌ساز محلی همچنان کار می‌کنه.'));}finally{clearTimeout(timer);busy=false;refresh();}}
function keydown(event){if(event.key!=='Enter'&&event.key!==' ')return false;const el=event.target?.closest?.('[data-extra-map-pin]');if(!el)return false;event.preventDefault();return click({target:el});}
window.MyHealthExtras={routes,labels,render,click,change,submit,keydown,init};
})();
